// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: attachments.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const bindAttachmentToMessage = `-- name: BindAttachmentToMessage :execrows
UPDATE attachment 
SET message_id = $3 
WHERE id = $1 AND conversation_id = $2 AND status = 'complete' AND message_id IS NULL
`

type BindAttachmentToMessageParams struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	MessageID      uuid.UUID
}

func (q *Queries) BindAttachmentToMessage(ctx context.Context, arg *BindAttachmentToMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindAttachmentToMessage, arg.ID, arg.ConversationID, arg.MessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAttachment = `-- name: CreateAttachment :one

INSERT INTO attachment (
  conversation_id, storage_key, file_name, content_type, size_bytes
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, conversation_id, message_id, storage_key, file_name, content_type, size_bytes, status, created_at
`

type CreateAttachmentParams struct {
	ConversationID uuid.UUID
	StorageKey     string
	FileName       string
	ContentType    string
	SizeBytes      *int64
}

// sqlc/queries/attachments.sql
func (q *Queries) CreateAttachment(ctx context.Context, arg *CreateAttachmentParams) (*Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ConversationID,
		arg.StorageKey,
		arg.FileName,
		arg.ContentType,
		arg.SizeBytes,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.MessageID,
		&i.StorageKey,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteOldInitAttachments = `-- name: DeleteOldInitAttachments :exec
DELETE FROM attachment 
WHERE status = 'init' AND created_at < $1
`

func (q *Queries) DeleteOldInitAttachments(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldInitAttachments, createdAt)
	return err
}

const findAttachmentById = `-- name: FindAttachmentById :one
SELECT id, conversation_id, message_id, storage_key, file_name, content_type, size_bytes, status, created_at
FROM attachment 
WHERE id = $1
`

func (q *Queries) FindAttachmentById(ctx context.Context, id uuid.UUID) (*Attachment, error) {
	row := q.db.QueryRow(ctx, findAttachmentById, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.MessageID,
		&i.StorageKey,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const findAttachmentsByConvId = `-- name: FindAttachmentsByConvId :many
SELECT id, conversation_id, message_id, storage_key, file_name, content_type, size_bytes, status, created_at
FROM attachment
WHERE conversation_id = $1
  AND id = ANY($2::uuid[])
`

type FindAttachmentsByConvIdParams struct {
	ConversationID uuid.UUID
	AttachmentIds  []uuid.UUID
}

func (q *Queries) FindAttachmentsByConvId(ctx context.Context, arg *FindAttachmentsByConvIdParams) ([]*Attachment, error) {
	rows, err := q.db.Query(ctx, findAttachmentsByConvId, arg.ConversationID, arg.AttachmentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.MessageID,
			&i.StorageKey,
			&i.FileName,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findByMessId = `-- name: FindByMessId :many
SELECT id, conversation_id, message_id, storage_key, file_name, content_type, size_bytes, status, created_at
FROM attachment 
WHERE message_id = $1
`

func (q *Queries) FindByMessId(ctx context.Context, messageID uuid.UUID) ([]*Attachment, error) {
	rows, err := q.db.Query(ctx, findByMessId, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.MessageID,
			&i.StorageKey,
			&i.FileName,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findByMessIds = `-- name: FindByMessIds :many
SELECT id, message_id
FROM attachment
WHERE message_id = ANY($1::uuid[])
`

type FindByMessIdsRow struct {
	ID        uuid.UUID
	MessageID uuid.UUID
}

func (q *Queries) FindByMessIds(ctx context.Context, messageIds []uuid.UUID) ([]*FindByMessIdsRow, error) {
	rows, err := q.db.Query(ctx, findByMessIds, messageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*FindByMessIdsRow
	for rows.Next() {
		var i FindByMessIdsRow
		if err := rows.Scan(&i.ID, &i.MessageID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttachmentComplete = `-- name: MarkAttachmentComplete :one
UPDATE attachment 
SET status = 'complete' 
WHERE id = $1 AND conversation_id = $2 AND status = 'init'
RETURNING id, conversation_id, message_id, storage_key, file_name, content_type, size_bytes, status, created_at
`

type MarkAttachmentCompleteParams struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
}

func (q *Queries) MarkAttachmentComplete(ctx context.Context, arg *MarkAttachmentCompleteParams) (*Attachment, error) {
	row := q.db.QueryRow(ctx, markAttachmentComplete, arg.ID, arg.ConversationID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.MessageID,
		&i.StorageKey,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}
