// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: conversations.sql

package store

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addParticipant = `-- name: AddParticipant :exec
INSERT INTO conversation_participant (conversation_id, user_id, role)
VALUES ($1, $2, $3) ON CONFLICT (conversation_id, user_id) DO NOTHING
`

type AddParticipantParams struct {
	ConversationID uuid.UUID
	UserID         uuid.UUID
	Role           string
}

func (q *Queries) AddParticipant(ctx context.Context, arg *AddParticipantParams) error {
	_, err := q.db.Exec(ctx, addParticipant, arg.ConversationID, arg.UserID, arg.Role)
	return err
}

const createConversation = `-- name: CreateConversation :one

INSERT INTO conversation (type,
                          status,
                          topic,
                          tg_support_chat_id,
                          tg_support_topic_id,
                          source,
                          page_url,
                          locale,
                          timezone,
                          app_version,
                          created_by)
VALUES ($1, -- type
        $2, -- status
        $3, -- topic
        $4, -- tg_support_chat_id
        $5, -- tg_support_topic_id
        $6, -- source
        $7, -- page_url
        $8, -- locale
        $9, -- timezone
        $10, -- app_version
        $11 -- created_by
       ) RETURNING
    id,
    type,
    status,
    topic,
    tg_support_chat_id,
    tg_support_topic_id,
    source,
    page_url,
    locale,
    timezone,
    app_version,
    is_like,
    created_by,
    created_at
`

type CreateConversationParams struct {
	Type             string
	Status           string
	Topic            *string
	TgSupportChatID  *int64
	TgSupportTopicID *int32
	Source           string
	PageUrl          *string
	Locale           *string
	Timezone         pgtype.Numeric
	AppVersion       *string
	CreatedBy        uuid.UUID
}

// sqlc/queries/conversations.sql
func (q *Queries) CreateConversation(ctx context.Context, arg *CreateConversationParams) (*Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.Type,
		arg.Status,
		arg.Topic,
		arg.TgSupportChatID,
		arg.TgSupportTopicID,
		arg.Source,
		arg.PageUrl,
		arg.Locale,
		arg.Timezone,
		arg.AppVersion,
		arg.CreatedBy,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Topic,
		&i.TgSupportChatID,
		&i.TgSupportTopicID,
		&i.Source,
		&i.PageUrl,
		&i.Locale,
		&i.Timezone,
		&i.AppVersion,
		&i.IsLike,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const findConversationById = `-- name: FindConversationById :one
SELECT id,
       type,
       status,
       topic,
       tg_support_chat_id,
       tg_support_topic_id,
       source,
       page_url,
       locale,
       timezone,
       app_version,
       is_like,
       created_by,
       created_at
FROM conversation
WHERE id = $1
`

func (q *Queries) FindConversationById(ctx context.Context, id uuid.UUID) (*Conversation, error) {
	row := q.db.QueryRow(ctx, findConversationById, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Topic,
		&i.TgSupportChatID,
		&i.TgSupportTopicID,
		&i.Source,
		&i.PageUrl,
		&i.Locale,
		&i.Timezone,
		&i.AppVersion,
		&i.IsLike,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const findConversationByThread = `-- name: FindConversationByThread :one
SELECT id,
       type,
       status,
       topic,
       tg_support_chat_id,
       tg_support_topic_id,
       source,
       page_url,
       locale,
       timezone,
       app_version,
       is_like,
       created_by,
       created_at
FROM conversation
WHERE tg_support_chat_id = $1
  AND tg_support_topic_id = $2 LIMIT 1
`

type FindConversationByThreadParams struct {
	TgSupportChatID  *int64
	TgSupportTopicID *int32
}

func (q *Queries) FindConversationByThread(ctx context.Context, arg *FindConversationByThreadParams) (*Conversation, error) {
	row := q.db.QueryRow(ctx, findConversationByThread, arg.TgSupportChatID, arg.TgSupportTopicID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Topic,
		&i.TgSupportChatID,
		&i.TgSupportTopicID,
		&i.Source,
		&i.PageUrl,
		&i.Locale,
		&i.Timezone,
		&i.AppVersion,
		&i.IsLike,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const findConversationsByUser = `-- name: FindConversationsByUser :many
SELECT
    c.id,
    c.type,
    c.status,
    c.topic,
    c.tg_support_chat_id,
    c.tg_support_topic_id,
    c.source,
    c.page_url,
    c.locale,
    c.timezone,
    c.app_version,
    c.is_like,
    c.created_by,
    c.created_at
FROM conversation c
         JOIN conversation_participant p ON p.conversation_id = c.id
WHERE p.user_id = $1
ORDER BY c.created_at DESC, c.id DESC
    LIMIT $2
`

type FindConversationsByUserParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) FindConversationsByUser(ctx context.Context, arg *FindConversationsByUserParams) ([]*Conversation, error) {
	rows, err := q.db.Query(ctx, findConversationsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.Topic,
			&i.TgSupportChatID,
			&i.TgSupportTopicID,
			&i.Source,
			&i.PageUrl,
			&i.Locale,
			&i.Timezone,
			&i.AppVersion,
			&i.IsLike,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOpenConversationByUserId = `-- name: FindOpenConversationByUserId :one
SELECT
    c.id, c.type, c.status, c.topic,
    c.tg_support_chat_id, c.tg_support_topic_id,
    c.source, c.page_url, c.locale, c.timezone, c.app_version, c.is_like,
    c.created_by, c.created_at
FROM conversation c
         JOIN conversation_participant p ON p.conversation_id = c.id
WHERE p.user_id = $1
  AND c.type = $2
  AND c.status IN ('open','pending')
ORDER BY c.created_at DESC
    LIMIT 1
`

type FindOpenConversationByUserIdParams struct {
	UserID uuid.UUID
	Type   string
}

func (q *Queries) FindOpenConversationByUserId(ctx context.Context, arg *FindOpenConversationByUserIdParams) (*Conversation, error) {
	row := q.db.QueryRow(ctx, findOpenConversationByUserId, arg.UserID, arg.Type)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Topic,
		&i.TgSupportChatID,
		&i.TgSupportTopicID,
		&i.Source,
		&i.PageUrl,
		&i.Locale,
		&i.Timezone,
		&i.AppVersion,
		&i.IsLike,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const isParticipant = `-- name: IsParticipant :one
SELECT EXISTS (SELECT 1
               FROM conversation_participant
               WHERE conversation_id = $1
                 AND user_id = $2) AS is_participant
`

type IsParticipantParams struct {
	ConversationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) IsParticipant(ctx context.Context, arg *IsParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isParticipant, arg.ConversationID, arg.UserID)
	var is_participant bool
	err := row.Scan(&is_participant)
	return is_participant, err
}

const updateConversationRating = `-- name: UpdateConversationRating :one
UPDATE conversation
SET is_like = $2
WHERE id = $1 RETURNING
    id,
    type,
    status,
    topic,
    tg_support_chat_id,
    tg_support_topic_id,
    source,
    page_url,
    locale,
    timezone,
    app_version,
    is_like,
    created_by,
    created_at
`

type UpdateConversationRatingParams struct {
	ID     uuid.UUID
	IsLike *bool
}

func (q *Queries) UpdateConversationRating(ctx context.Context, arg *UpdateConversationRatingParams) (*Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversationRating, arg.ID, arg.IsLike)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Topic,
		&i.TgSupportChatID,
		&i.TgSupportTopicID,
		&i.Source,
		&i.PageUrl,
		&i.Locale,
		&i.Timezone,
		&i.AppVersion,
		&i.IsLike,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const updateConversationStatus = `-- name: UpdateConversationStatus :one
UPDATE conversation
SET status = $2
WHERE id = $1 RETURNING
    id,
    type,
    status,
    topic,
    tg_support_chat_id,
    tg_support_topic_id,
    source,
    page_url,
    locale,
    timezone,
    app_version,
    is_like,
    created_by,
    created_at
`

type UpdateConversationStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateConversationStatus(ctx context.Context, arg *UpdateConversationStatusParams) (*Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversationStatus, arg.ID, arg.Status)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Topic,
		&i.TgSupportChatID,
		&i.TgSupportTopicID,
		&i.Source,
		&i.PageUrl,
		&i.Locale,
		&i.Timezone,
		&i.AppVersion,
		&i.IsLike,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const updateTelegramInfo = `-- name: UpdateTelegramInfo :one
UPDATE conversation
SET tg_support_chat_id = $2,
    tg_support_topic_id = $3
WHERE id = $1 RETURNING
    id,
    type,
    status,
    topic,
    tg_support_chat_id,
    tg_support_topic_id,
    source,
    page_url,
    locale,
    timezone,
    app_version,
    is_like,
    created_by,
    created_at
`

type UpdateTelegramInfoParams struct {
	ID               uuid.UUID
	TgSupportChatID  *int64
	TgSupportTopicID *int32
}

func (q *Queries) UpdateTelegramInfo(ctx context.Context, arg *UpdateTelegramInfoParams) (*Conversation, error) {
	row := q.db.QueryRow(ctx, updateTelegramInfo, arg.ID, arg.TgSupportChatID, arg.TgSupportTopicID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Topic,
		&i.TgSupportChatID,
		&i.TgSupportTopicID,
		&i.Source,
		&i.PageUrl,
		&i.Locale,
		&i.Timezone,
		&i.AppVersion,
		&i.IsLike,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}
