// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package store

import (
	"context"

	uuid "github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one

INSERT INTO message (
  conversation_id, sender_kind, source, content_type, content_text, client_id, tg_message_id, reply_to_message_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, conversation_id, seq_no, sender_kind, source, content_type, content_text, client_id, tg_message_id, reply_to_message_id, created_at
`

type CreateMessageParams struct {
	ConversationID   uuid.UUID
	SenderKind       string
	Source           string
	ContentType      string
	ContentText      *string
	ClientID         *string
	TgMessageID      *int64
	ReplyToMessageID *uuid.UUID
}

// sqlc/queries/messages.sql
func (q *Queries) CreateMessage(ctx context.Context, arg *CreateMessageParams) (*Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.SenderKind,
		arg.Source,
		arg.ContentType,
		arg.ContentText,
		arg.ClientID,
		arg.TgMessageID,
		arg.ReplyToMessageID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SeqNo,
		&i.SenderKind,
		&i.Source,
		&i.ContentType,
		&i.ContentText,
		&i.ClientID,
		&i.TgMessageID,
		&i.ReplyToMessageID,
		&i.CreatedAt,
	)
	return &i, err
}

const findMessageByClientId = `-- name: FindMessageByClientId :one
SELECT id, conversation_id, seq_no, sender_kind, source, content_type, content_text, client_id, tg_message_id, reply_to_message_id, created_at
FROM message 
WHERE conversation_id = $1 AND client_id = $2
`

type FindMessageByClientIdParams struct {
	ConversationID uuid.UUID
	ClientID       *string
}

func (q *Queries) FindMessageByClientId(ctx context.Context, arg *FindMessageByClientIdParams) (*Message, error) {
	row := q.db.QueryRow(ctx, findMessageByClientId, arg.ConversationID, arg.ClientID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SeqNo,
		&i.SenderKind,
		&i.Source,
		&i.ContentType,
		&i.ContentText,
		&i.ClientID,
		&i.TgMessageID,
		&i.ReplyToMessageID,
		&i.CreatedAt,
	)
	return &i, err
}

const findMessageByConvId = `-- name: FindMessageByConvId :many
SELECT id, conversation_id, seq_no, sender_kind, source, content_type, content_text, client_id, tg_message_id, reply_to_message_id, created_at
FROM message
WHERE conversation_id = $1 AND seq_no > $2
ORDER BY seq_no ASC
LIMIT $3
`

type FindMessageByConvIdParams struct {
	ConversationID uuid.UUID
	SeqNo          int64
	Limit          int32
}

func (q *Queries) FindMessageByConvId(ctx context.Context, arg *FindMessageByConvIdParams) ([]*Message, error) {
	rows, err := q.db.Query(ctx, findMessageByConvId, arg.ConversationID, arg.SeqNo, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SeqNo,
			&i.SenderKind,
			&i.Source,
			&i.ContentType,
			&i.ContentText,
			&i.ClientID,
			&i.TgMessageID,
			&i.ReplyToMessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMessageByConvIdDesc = `-- name: FindMessageByConvIdDesc :many
SELECT id, conversation_id, seq_no, sender_kind, source, content_type, content_text, client_id, tg_message_id, reply_to_message_id, created_at
FROM message
WHERE conversation_id = $1 AND seq_no > $2
ORDER BY seq_no DESC
    LIMIT $3
`

type FindMessageByConvIdDescParams struct {
	ConversationID uuid.UUID
	SeqNo          int64
	Limit          int32
}

func (q *Queries) FindMessageByConvIdDesc(ctx context.Context, arg *FindMessageByConvIdDescParams) ([]*Message, error) {
	rows, err := q.db.Query(ctx, findMessageByConvIdDesc, arg.ConversationID, arg.SeqNo, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SeqNo,
			&i.SenderKind,
			&i.Source,
			&i.ContentType,
			&i.ContentText,
			&i.ClientID,
			&i.TgMessageID,
			&i.ReplyToMessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastSeq = `-- name: GetLastSeq :one
SELECT COALESCE(MAX(seq_no), 0) AS last_seq
FROM message
WHERE conversation_id = $1
`

func (q *Queries) GetLastSeq(ctx context.Context, conversationID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getLastSeq, conversationID)
	var last_seq interface{}
	err := row.Scan(&last_seq)
	return last_seq, err
}

const updateMessageTelegramId = `-- name: UpdateMessageTelegramId :exec
UPDATE message SET tg_message_id = $2 WHERE id = $1
`

type UpdateMessageTelegramIdParams struct {
	ID          uuid.UUID
	TgMessageID *int64
}

func (q *Queries) UpdateMessageTelegramId(ctx context.Context, arg *UpdateMessageTelegramIdParams) error {
	_, err := q.db.Exec(ctx, updateMessageTelegramId, arg.ID, arg.TgMessageID)
	return err
}
