// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppUser struct {
	ID        uuid.UUID
	Username  string
	CreatedAt time.Time
}

type Attachment struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	MessageID      *uuid.UUID
	StorageKey     string
	FileName       string
	ContentType    string
	SizeBytes      *int64
	Status         string
	CreatedAt      time.Time
}

type Conversation struct {
	ID               uuid.UUID
	Type             string
	Status           string
	Topic            *string
	TgSupportChatID  *int64
	TgSupportTopicID *int32
	Source           string
	PageUrl          *string
	Locale           *string
	Timezone         pgtype.Numeric
	AppVersion       *string
	IsLike           *bool
	CreatedBy        uuid.UUID
	CreatedAt        time.Time
}

type Message struct {
	ID               uuid.UUID
	ConversationID   uuid.UUID
	SeqNo            int64
	SenderKind       string
	Source           string
	ContentType      string
	ContentText      *string
	ClientID         *string
	TgMessageID      *int64
	ReplyToMessageID *uuid.UUID
	CreatedAt        time.Time
}
