// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

type Querier interface {
	AddParticipant(ctx context.Context, arg *AddParticipantParams) error
	BindAttachmentToMessage(ctx context.Context, arg *BindAttachmentToMessageParams) (int64, error)
	// sqlc/queries/attachments.sql
	CreateAttachment(ctx context.Context, arg *CreateAttachmentParams) (*Attachment, error)
	// sqlc/queries/conversations.sql
	CreateConversation(ctx context.Context, arg *CreateConversationParams) (*Conversation, error)
	// sqlc/queries/messages.sql
	CreateMessage(ctx context.Context, arg *CreateMessageParams) (*Message, error)
	// sqlc/queries/user.sql
	CreateUser(ctx context.Context, arg *CreateUserParams) (*AppUser, error)
	DeleteOldInitAttachments(ctx context.Context, createdAt time.Time) error
	FindAttachmentById(ctx context.Context, id uuid.UUID) (*Attachment, error)
	FindAttachmentsByConvId(ctx context.Context, arg *FindAttachmentsByConvIdParams) ([]*Attachment, error)
	FindByMessId(ctx context.Context, messageID uuid.UUID) ([]*Attachment, error)
	FindByMessIds(ctx context.Context, messageIds []uuid.UUID) ([]*FindByMessIdsRow, error)
	FindConversationById(ctx context.Context, id uuid.UUID) (*Conversation, error)
	FindConversationByThread(ctx context.Context, arg *FindConversationByThreadParams) (*Conversation, error)
	FindConversationsByUser(ctx context.Context, arg *FindConversationsByUserParams) ([]*Conversation, error)
	FindMessageByClientId(ctx context.Context, arg *FindMessageByClientIdParams) (*Message, error)
	FindMessageByConvId(ctx context.Context, arg *FindMessageByConvIdParams) ([]*Message, error)
	FindMessageByConvIdDesc(ctx context.Context, arg *FindMessageByConvIdDescParams) ([]*Message, error)
	FindOpenConversationByUserId(ctx context.Context, arg *FindOpenConversationByUserIdParams) (*Conversation, error)
	FindUserByID(ctx context.Context, id uuid.UUID) (*AppUser, error)
	GetLastSeq(ctx context.Context, conversationID uuid.UUID) (interface{}, error)
	IsParticipant(ctx context.Context, arg *IsParticipantParams) (bool, error)
	MarkAttachmentComplete(ctx context.Context, arg *MarkAttachmentCompleteParams) (*Attachment, error)
	UpdateConversationRating(ctx context.Context, arg *UpdateConversationRatingParams) (*Conversation, error)
	UpdateConversationStatus(ctx context.Context, arg *UpdateConversationStatusParams) (*Conversation, error)
	UpdateMessageTelegramId(ctx context.Context, arg *UpdateMessageTelegramIdParams) error
	UpdateTelegramInfo(ctx context.Context, arg *UpdateTelegramInfoParams) (*Conversation, error)
}

var _ Querier = (*Queries)(nil)
