// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package store

import (
	"context"

	uuid "github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one

INSERT INTO app_user (id,
                      username)
VALUES ($1, $2) RETURNING
    id,
    username,
    created_at
`

type CreateUserParams struct {
	ID       uuid.UUID
	Username string
}

// sqlc/queries/user.sql
func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*AppUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Username)
	var i AppUser
	err := row.Scan(&i.ID, &i.Username, &i.CreatedAt)
	return &i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id,
       username,
       created_at
FROM app_user
WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (*AppUser, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i AppUser
	err := row.Scan(&i.ID, &i.Username, &i.CreatedAt)
	return &i, err
}
