# Build stage
FROM golang:1.25.0-alpine AS builder
WORKDIR /app

RUN apk add --no-cache git ca-certificates tzdata

COPY go.mod go.sum ./
COPY cmd/migrate ./cmd/migrate
COPY internal ./internal
COPY db ./db
COPY configs ./configs

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -a -o migrate ./cmd/migrate

# Runtime stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates tzdata

WORKDIR /app

COPY --from=builder /app/migrate .
COPY --from=builder /app/configs ./configs

CMD ["./migrate"]
